### ISSUE TITLE
Expand documentation 

### ISSUE THREAD

**Issue by PBBlomquist** [appliedepi/appliedepidata#10]
In the 'adding data' vignette, add detail on:

- [x] Building the package (so that the system.file() function will work when internalising datasets)
- [x] Running roxygenize() or similar to generate the R documentation from the *_doc.R files

(I'm happy to help with this)

**Comment by aspina7** [comment]
yes please could you add this? 
also would use devtools::document() instead of roxygenize()
I have also rename *_doc.R files to match the group name from *tableoftables*.

**Comment by PBBlomquist** [comment]
Okay have added - 92d4768310685dc7bd1682bfd4b1af76bec93c96

Not finalised as want to clarify a few things:

- Can I remove mentions of `sysdata` and `internal data` folders? They don't exist, but should they at some point?
- Should data only be added to `inst/extdata` now? Is the original data (for save_data()) in `inst/extdata` and internalized data (for get_data()) generated in `data`?

Following on from that, is it correct that:

- The same data (structure/content) should be accessible via get_data() and save_data(), differing only by file type and import needs?
- Therefore If an original file needs major processing before it is suitable for use, it should be saved in inst/extdata and processed in the raw_data R script to create and then internalize a version2.  Again this means the processed version can be accessed via both get_data() or save_data(). 
- An .rda file should also be saved in inst/extdata if it's the original file?

**Comment by aspina7** [comment]
>     * Can I remove mentions of `sysdata` and `internal data` folders? They don't exist, but should they at some point?

Yes think remove `sysdata` - I would just mention data internalisation under the `data` folder bullet point. Neither of these folders should exist.

>     * Should data only be added to `inst/extdata` now? Is the original data (for save_data()) in `inst/extdata` and internalized data (for get_data()) generated in `data`?

yes correct 

> Following on from that, is it correct that:
> 
>     * The same data (structure/content) should be accessible via get_data() and save_data(), differing only by file type and import needs?

yes correct 


>     * Therefore If an original file needs major processing before it is suitable for use, it should be saved in inst/extdata and processed in the raw_data R script to create and then internalize a version2.  Again this means the processed version can be accessed via both get_data() or save_data().

yes if creating a version two would need to export to both `inst/extdata` and `data ` and then add a line to tableoftables

>     * An .rda file should also be saved in inst/extdata if it's the original file?

I guess so yeah...
