### ISSUE TITLE
Duplicate clean Fulton files

### ISSUE THREAD

**Issue by PBBlomquist** [appliedepi/appliedepidata#11]
I've added fulton_data.rds to the data folder as instructed, but the process ends up creating a fulton_data.rda. Seems unnecessary but leaving it to Alex to adjust!

6e670431dcc518941f1c3a8406a30d8d93448bb6

**Comment by aspina7** [comment]
address in this commit 5791ce796bd80ae4c1c07f743ed2dbffadf5f2af - as per this https://github.com/appliedepi/appliedepidata/pull/12#issuecomment-2351786404
